name: "Bug Report"
description: "Report a bug in the project"
title: "[Bug]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.
        Please provide the following details to help us address the issue promptly.
  - type: input
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the bug"
      placeholder: "1. Go to...\n2. Click on...\n3. Scroll down to...\n4. See error"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior"
      description: "Describe what you expected to happen"
      placeholder: "The application should..."
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior"
      description: "Describe what actually happened"
      placeholder: "Instead of the expected behavior, the application..."
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: "Environment"
      description: "Provide details about your environment"
      placeholder: "OS, Browser, Version, etc."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context about the problem here"
      placeholder: "Screenshots, logs, or any other relevant information"
    validations:
      required: false
