name: "Feature Request"
description: "Suggest a new feature or enhancement"
title: "[Feature Request]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        We appreciate your suggestions to improve our project.
        Please provide the following details to help us understand your request.
  - type: input
    id: feature-description
    attributes:
      label: "Feature Description"
      description: "Briefly describe the feature you would like to see"
      placeholder: "I would like to have..."
    validations:
      required: true
  - type: textarea
    id: use-case
    attributes:
      label: "Use Case"
      description: "Explain how this feature would be used and why it's beneficial"
      placeholder: "This feature would allow users to..."
    validations:
      required: true
  - type: input
    id: alternatives
    attributes:
      label: "Alternatives Considered"
      description: "Have you considered any alternative solutions?"
      placeholder: "An alternative solution could be..."
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request"
      placeholder: "Additional information..."
    validations:
      required: false
